@baseUrl = http://localhost:3001

# Customer

# @name criar_cliente
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "document": "111.444.777-35"
}

###

# @name obter_cliente_por_cpf
GET {{baseUrl}}/customers/11144477735

